"""change text to unicode

Revision ID: 1eff94afdca1
Revises: 2653b38097cf
Create Date: 2021-05-19 22:56:21.586748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eff94afdca1'
down_revision = '2653b38097cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'image')
    op.drop_column('stock', 'ticker')
    op.drop_column('stock', 'segment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('segment', sa.TEXT(), nullable=False))
    op.add_column('stock', sa.Column('ticker', sa.TEXT(), nullable=False))
    op.add_column('stock', sa.Column('image', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
