"""change text to unicode

Revision ID: 2a4585981398
Revises: 3d8c45912f04
Create Date: 2021-05-19 22:55:56.875097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4585981398'
down_revision = '3d8c45912f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('name', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
