"""empty message

Revision ID: b4fc71f2dd67
Revises: e1b2984cde31
Create Date: 2021-05-19 23:17:21.693394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fc71f2dd67'
down_revision = 'e1b2984cde31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('segment')
        batch_op.drop_column('name')
        batch_op.drop_column('image')
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('segment', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
