"""change text to unicode

Revision ID: d26e4b912859
Revises: 1eff94afdca1
Create Date: 2021-05-19 22:56:34.010839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26e4b912859'
down_revision = '1eff94afdca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('image', sa.Unicode(), nullable=False))
    op.add_column('stock', sa.Column('segment', sa.Unicode(), nullable=False))
    op.add_column('stock', sa.Column('ticker', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'ticker')
    op.drop_column('stock', 'segment')
    op.drop_column('stock', 'image')
    # ### end Alembic commands ###
