"""empty message

Revision ID: e1b2984cde31
Revises: 09ad485ea555
Create Date: 2021-05-19 23:06:16.759049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b2984cde31'
down_revision = '09ad485ea555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('image', sa.Unicode(), nullable=False))
    op.add_column('stock', sa.Column('name', sa.Unicode(), nullable=False))
    op.add_column('stock', sa.Column('segment', sa.Unicode(), nullable=False))
    op.add_column('stock', sa.Column('ticker', sa.Unicode(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'ticker')
    op.drop_column('stock', 'segment')
    op.drop_column('stock', 'name')
    op.drop_column('stock', 'image')
    # ### end Alembic commands ###
