"""empty message

Revision ID: f4e6b55b95d4
Revises: b4fc71f2dd67
Create Date: 2021-05-19 23:17:27.634921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e6b55b95d4'
down_revision = 'b4fc71f2dd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Unicode(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.Unicode(), nullable=True))
        batch_op.add_column(sa.Column('segment', sa.Unicode(), nullable=True))
        batch_op.add_column(sa.Column('ticker', sa.Unicode(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('ticker')
        batch_op.drop_column('segment')
        batch_op.drop_column('name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
